### ISSUE TITLE
Integer typos

### ISSUE THREAD

**Issue by ajkeller34** [PainterQubits/InstrumentControl.jl#22]
https://github.com/PainterQubits/InstrumentControl.jl/blob/da33b9622e657f5119bb6613365f3349f0091e0f/src/instruments/AWGs/M320XA/Waveform.jl#L202

Here and elsewhere, `Interger` should be `Integer`. Suggest doing find and replace in all files.

**Comment by ajkeller34** [comment]
Closed in commit f13df278e8fd3a01d42b75ef268a60d3d371abab

**Comment by vtdsferreira** [comment]
Thanks for taking care of this Andrew. I have merged the InstrumentControl master with my local branch; the next time I push to git I will have the (among other things) the Array{Real} issue you mentioned to me fixed as well
